# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTjKgjqbK83NZUQsjrwfS1GTWREn9KUn
"""

# ================================
# CONNECTED COMPONENT ANALYSIS (CCA)
# using OpenCV in Google Colab
# ================================

# Step 1: Import necessary libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 2: Upload an image
from google.colab import files
uploaded = files.upload()

# Get uploaded file path
for file_name in uploaded.keys():
    img_path = file_name

# Step 3: Read image and convert to grayscale
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

# Step 4: Apply binary thresholding
# (We can use global thresholding here)
_, binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# Step 5: Perform connected component analysis
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(binary, connectivity=8)

print(f"Number of connected components found (including background): {num_labels}")

# Step 6: Create a color map for visualization
# (Map each label to a random color)
label_hue = np.uint8(179 * labels / np.max(labels))
blank_ch = 255 * np.ones_like(label_hue)
colored_img = cv2.merge([label_hue, blank_ch, blank_ch])

# Convert from HSV to BGR for display
colored_img = cv2.cvtColor(colored_img, cv2.COLOR_HSV2RGB)
colored_img[label_hue == 0] = 0  # Set background to black

# Step 7: Display results
plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(img, cmap='gray')
plt.axis('off')

plt.subplot(1,2,2)
plt.title("Connected Components")
plt.imshow(colored_img)
plt.axis('off')

plt.show()

# Step 8: Display details for each component (excluding background)
for i in range(1, num_labels):
    x, y, w, h, area = stats[i]
    cx, cy = centroids[i]
    print(f"Component {i}: Area={area}, Centroid=({cx:.2f}, {cy:.2f}), BoundingBox=({x},{y},{w},{h})")

# Step 9: Save result
cv2.imwrite("connected_components_output.jpg", cv2.cvtColor(colored_img, cv2.COLOR_RGB2BGR))
print("Result image saved as 'connected_components_output.jpg'")


