# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13w1hjfqq6qFHDuVu9zpDQRkv2Kfq7YuC
"""

# Install dependencies
!pip install opencv-python matplotlib

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 1: Upload an image
print("📸 Upload an image for circle detection")
uploaded = files.upload()

# Step 2: Read the uploaded image
filename = next(iter(uploaded))
img = cv2.imread(filename)
output = img.copy()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Step 3: Apply a blur to reduce noise
gray = cv2.medianBlur(gray, 5)

# Step 4: Detect circles using Hough Transform
circles = cv2.HoughCircles(
    gray,
    cv2.HOUGH_GRADIENT,
    dp=1.2,          # Inverse ratio of accumulator resolution
    minDist=50,      # Minimum distance between detected circle centers
    param1=100,      # Higher threshold for Canny edge detector
    param2=30,       # Accumulator threshold for circle detection
    minRadius=10,    # Minimum circle radius
    maxRadius=200    # Maximum circle radius
)

# Step 5: Draw detected circles
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        # draw the outer circle
        cv2.circle(output, (i[0], i[1]), i[2], (0, 255, 0), 3)
        # draw the center of the circle
        cv2.circle(output, (i[0], i[1]), 2, (0, 0, 255), 3)

# Step 6: Display results
plt.figure(figsize=(15,7))
plt.subplot(1,2,1)
plt.title("

# Install dependencies
!pip install opencv-python matplotlib

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 1: Upload an image
print("📸 Upload an image for circle detection")
uploaded = files.upload()

# Step 2: Read the uploaded image
filename = next(iter(uploaded))
img = cv2.imread(filename)
output = img.copy()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Step 3: Apply a blur to reduce noise
gray = cv2.medianBlur(gray, 5)

# Step 4: Detect circles using Hough Transform
circles = cv2.HoughCircles(
    gray,
    cv2.HOUGH_GRADIENT,
    dp=1.2,          # Inverse ratio of accumulator resolution
    minDist=50,      # Minimum distance between detected circle centers
    param1=100,      # Higher threshold for Canny edge detector
    param2=30,       # Accumulator threshold for circle detection
    minRadius=10,    # Minimum circle radius
    maxRadius=200    # Maximum circle radius
)

# Step 5: Draw detected circles
if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        # draw the outer circle
        cv2.circle(output, (i[0], i[1]), i[2], (0, 255, 0), 3)
        # draw the center of the circle
        cv2.circle(output, (i[0], i[1]), 2, (0, 0, 255), 3)

# Step 6: Display results
plt.figure(figsize=(15,7))
plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

plt.subplot(1,2,2)
plt.title("Detected Circles using Hough Transform")
plt.imshow(cv2.cvtColor(output, cv2.COLOR_BGR2RGB))
plt.show()
