# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktceHIg7hyMTsptIdlA5w31N2APQ39tM
"""

# Install dependencies
!pip install opencv-python matplotlib numpy

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 1: Upload a road image
print("📸 Upload a road image with visible lane markings")
uploaded = files.upload()

# Step 2: Read the uploaded image
filename = next(iter(uploaded))
image = cv2.imread(filename)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Step 3: Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

# Step 4: Apply Gaussian blur to reduce noise
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# Step 5: Edge detection using Canny
edges = cv2.Canny(blur, 50, 150)

# Step 6: Define region of interest (ROI)
height = image.shape[0]
polygon = np.array([
    [(0, height), (image.shape[1], height), (image.shape[1]//2, int(height*0.6))]
])
mask = np.zeros_like(edges)
cv2.fillPoly(mask, polygon, 255)
masked_edges = cv2.bitwise_and(edges, mask)

# Step 7: Apply Hough Line Transform
lines = cv2.HoughLinesP(
    masked_edges,
    rho=2,
    theta=np.pi/180,
    threshold=100,
    minLineLength=40,
    maxLineGap=150
)

# Step 8: Draw detected lines
line_image = np.zeros_like(image)
if lines is not None:
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(line_image, (x1, y1), (x2, y2), (255, 0, 0), 10)

# Combine the original image with line overlay
combined = cv2.addWeighted(image, 0.8, line_image, 1, 1)

# Step 9: Display the results
plt.figure(figsize=(15,8))
plt.subplot(1,2,1)
plt.title("Original Road Image")
plt.imshow(image)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Detected Lane Lines using Hough Transform")
plt.imshow(combined)
plt.axis("off")
plt.show()
