# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTjKgjqbK83NZUQsjrwfS1GTWREn9KUn
"""

# ==========================
# GLOBAL THRESHOLDING - OpenCV
# ==========================

# Step 1: Import libraries
import cv2
import matplotlib.pyplot as plt

# Step 2: Upload an image (grayscale preferred)
from google.colab import files
uploaded = files.upload()

# Get the uploaded filename
for file_name in uploaded.keys():
    img_path = file_name

# Step 3: Read the image in grayscale
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

# Step 4: Apply global thresholding
# You can adjust the threshold value (e.g., 127)
thresh_value = 127
ret, thresh_img = cv2.threshold(img, thresh_value, 255, cv2.THRESH_BINARY)

# Step 5: Display results
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(img, cmap='gray')
plt.axis('off')

plt.subplot(1,2,2)
plt.title(f"Global Thresholding (T={thresh_value})")
plt.imshow(thresh_img, cmap='gray')
plt.axis('off')

plt.show()

# Step 6: Save the thresholded image
cv2.imwrite("thresholded_image.jpg", thresh_img)
print("Thresholded image saved as 'thresholded_image.jpg'")


